source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'WeatherApp' do
  pod 'GooglePlaces'
  pod 'Moya', '~> 11.0'
  pod 'Unbox'

  target 'WeatherAppTests' do
    pod 'Moya', '~> 11.0'
  end
end
